config/routes.rb
Rails.application.routes.draw do

  get   'credits'           => 'pages#credits'

  get   'signin'            => 'sessions#new'

  post  'signin'            => 'sessions#create'

  get   'signout'           => 'sessions#destroy'

  get   'signup'            => 'users#new'

  post  'signup'            => 'users#create'

  get   'profile'           => 'users#show_profile'

  get   'profile/:username' => 'users#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #concern :schedulable do
  #  resources :schedules, only: [:show, :edit, :update, :destroy, :new, :create] do
  #   collection do
  #      get 'list' => 'schedules#list'
  #    end
  #  end
  #end
  
  root :to => 'home#index'

resources :users, only: [:edit, :update, :destroy] do
  resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
    resources :events, only: [:show, :edit, :update, :destroy, :new, :create]
  end
  collection do
    get 'groups' => 'users#groups'
  end
end

  resources :groups, only: [:edit, :update, :destroy, :new, :create] do
    resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create]
    collection do
      get 'users' => 'groups#users'
    end
  end
  
end

app/models/schedule.rb
class Schedule
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  
  field 		:t, as: :title,   type: String
  embeds_many	:schedule_events, as: :having_schedule_events, store_as: "evs"
  embedded_in 	:having_schedule, polymorphic: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  include SchedulesHelper
  include ParentHelper

  before_action :find_parent

  def index
    @schedules = @parents[0].schedules
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(new_schedule_params)
    @parents[0].schedules.push @schedule
    if @parents[0].save
      @schedules = @parents[0].schedules
      render 'index'
    else
      render 'new'
    end
  end

  def show
    @schedule = @parents[0].schedules.find(params[:id])
    @events_hash = get_events_hash @schedule
  end

  def destroy
    @parents[0].schedules.find(params[:id]).destroy
    redirect_to action: :index, "#{@parents[0].class.to_s.downcase}_id".to_sym => @parents[0].id
  end

  private
  
  def new_schedule_params
    params.require(:schedule)
      .permit(:title)
  end 
end

app/helpers/schedules_helper.rb
module SchedulesHelper
	def get_events_hash schedule
		h = Hash.new

    	(Week.monday..Week.saturday).each do |n|
      		h[n] = schedule.events.where[day: n]
    	end
    	h
	end
end

app/views/schedules/_schedule_desc.html.erb
<dt><%= schedule.title %>

<div class="uk-button-group">
  <%= link_to 'open', user_schedule_path(user_id: current_user.id, id: schedule.id), class: "uk-button uk-button-default uk-button-small"%>
  <%= link_to 'rename', edit_user_schedule_path(user_id: current_user.id, id: schedule.id), class: "uk-button uk-button-default uk-button-small" %>
  <%= link_to 'delete', user_schedule_path(user_id: current_user.id, id: schedule.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "uk-button uk-button-default uk-button-small" %>
</div>
</dt>
<dd>
</dd>

app/views/schedules/index.html.erb
<div class="uk-section uk-section-default">
	<div class="uk-container">
		<div class="uk-grid-match uk-child-width-1-1@m" uk-grid>
			<div>
				<% if @schedules.empty? %>
				<p>You have not any schedules yet. Make the <%= link_to 'first one', new_user_schedule_path, html_options = { class: "" } %>!</p>
				<% else %>
				<dl class="uk-description-list uk-description-list-divider">
					<% @schedules.each do |schedule|%>
					<%= render partial: 'schedules/schedule_desc', locals: {schedule: schedule} %>
					<% end %>
				</dl>		
				<p>Would you like to create <%= link_to 'one more', new_user_schedule_path, html_options = { class: "" } %>?</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/schedules/new.html.erb
<article>
<%= form_for @schedule, url: user_schedules_path do |f| %>
    <fieldset class="flex third center">
      <label>
        <%= f.text_field :title, class: "", placeholder: "Title" %>
      </label>
      <label>
        <%= f.submit "Save", class: "button" %>
      </label>
    </fieldset>
  <% end %>
</article>

app/views/schedules/show.html.erb
<div class="uk-section uk-section-default">
  <div class="uk-container">
    <div class="uk-grid-match uk-child-width-1-2@m" uk-grid>
      <div>
        <h2>
        <%= @schedule.title %>
        <%= link_to 'add event', new_user_schedule_event_path(user_id: current_user.id, schedule_id: @schedule.id), html_options = { class: "label" } %></h2>
        <div class="grid">
          <div class="cell grid-header">header</div>
          <div class="cell row1 col1"></div>
          <div class="cell row1 col2">Monday</div>
          <div class="cell row1 col3">Tuesday</div>
          <div class="cell row1 col4">Wednesday</div>
          <div class="cell row1 col5">Thursday</div>
          <div class="cell row1 col6">Friday</div>
          <div class="cell row1 col7">Saturday</div>
          
          <% @monday = @events_hash[Week.monday] %>
          <% @tuesday = @events_hash[Week.tuesday] %>
          <% @wednesday = @events_hash[Week.wednesday] %>
          <% @thursday = @events_hash[Week.thursday] %>
          <% @friday = @events_hash[Week.friday] %>
          <% @saturday = @events_hash[Week.saturday] %>
          <div class="cell row2 col1">1</div>
          <div class="item row2 col2"><article><%= render partial: "events/event", object: @monday[0] %></article></div>
          <div class="item row2 col3"><article><%= render partial: "events/event", object: @tuesday[0] %></article></div>
          <div class="item row2 col4"><article><%= render partial: "events/event", object: @wednesday[0] %></article></div>
          <div class="item row2 col5"><article><%= render partial: "events/event", object: @thursday[0] %></article></div>
          <div class="item row2 col6"><article><%= render partial: "events/event", object: @friday[0] %></article></div>
          <div class="item row2 col7"><article><%= render partial: "events/event", object: @saturday[0] %></article></div>
          
          <div class="cell row3 col1">2</div>
          <div class="item row3 col2"><article><%= render partial: "events/event", object: @monday[1] %></article></div>
          <div class="item row3 col3"><article><%= render partial: "events/event", object: @tuesday[1] %></article></div>
          <div class="item row3 col4"><article><%= render partial: "events/event", object: @wednesday[1] %></article></div>
          <div class="item row3 col5"><article><%= render partial: "events/event", object: @thursday[1] %></article></div>
          <div class="item row3 col6"><article><%= render partial: "events/event", object: @friday[1] %></article></div>
          <div class="item row3 col7"><article><%= render partial: "events/event", object: @saturday[1] %></article></div>
          
          <div class="cell row4 col1">3</div>
          <div class="item row4 col2"><article><%= render partial: "events/event", object: @monday[2] %></article></div>
          <div class="item row4 col3"><article><%= render partial: "events/event", object: @tuesday[2] %></article></div>
          <div class="item row4 col4"><article><%= render partial: "events/event", object: @wednesday[2] %></article></div>
          <div class="item row4 col5"><article><%= render partial: "events/event", object: @thursday[2] %></article></div>
          <div class="item row4 col6"><article><%= render partial: "events/event", object: @friday[2] %></article></div>
          <div class="item row4 col7"><article><%= render partial: "events/event", object: @saturday[2] %></article></div>
          
          <div class="cell row5 col1">4</div>
          <div class="item row5 col2"><article><%= render partial: "events/event", object: @monday[3] %></article></div>
          <div class="item row5 col3"><article><%= render partial: "events/event", object: @tuesday[3] %></article></div>
          <div class="item row5 col4"><article><%= render partial: "events/event", object: @wednesday[3] %></article></div>
          <div class="item row5 col5"><article><%= render partial: "events/event", object: @thursday[3] %></article></div>
          <div class="item row5 col6"><article><%= render partial: "events/event", object: @friday[3] %></article></div>
          <div class="item row5 col7"><article><%= render partial: "events/event", object: @saturday[3] %></article></div>
          <div class="cell row6 col1">5</div>
          <div class="item row6 col2"><article><%= render partial: "events/event", object: @monday[4] %></article></div>
          <div class="item row6 col3"><article><%= render partial: "events/event", object: @tuesday[4] %></article></div>
          <div class="item row6 col4"><article><%= render partial: "events/event", object: @wednesday[4] %></article></div>
          <div class="item row6 col5"><article><%= render partial: "events/event", object: @thursday[4] %></article></div>
          <div class="item row6 col6"><article><%= render partial: "events/event", object: @friday[4] %></article></div>
          <div class="item row6 col7"><article><%= render partial: "events/event", object: @saturday[4] %></article></div>
          <div class="cell grid-footer">footer</div>
        </div>
      </div>
      <div>
        
      </div>
    </div>
  </div>
</div>