config/routes.rb
Rails.application.routes.draw do

  get   'credits'           => 'pages#credits'

  get   'signin'            => 'sessions#new'

  post  'signin'            => 'sessions#create'

  get   'signout'           => 'sessions#destroy'

  get   'signup'            => 'users#new'

  post  'signup'            => 'users#create'

  get   'profile'           => 'users#show_profile'

  get   'profile/:username' => 'users#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #concern :schedulable do
  #  resources :schedules, only: [:show, :edit, :update, :destroy, :new, :create] do
  #   collection do
  #      get 'list' => 'schedules#list'
  #    end
  #  end
  #end
  
  root :to => 'home#index'

resources :users, only: [:edit, :update, :destroy] do
  resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
    resources :events, only: [:show, :edit, :update, :destroy, :new, :create]
  end
  collection do
    get 'groups' => 'users#groups'
  end
end

  resources :groups, only: [:edit, :update, :destroy, :new, :create] do
    resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create]
    collection do
      get 'users' => 'groups#users'
    end
  end
  
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  field :title
  field :body
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
include TimeHelper

def new
  @event = params[:ev_t].classify.constantize.new
  @parent_id = params[:p_id]
end

def create

end

def destroy

end

def new_schedule_event_params

  params[:schedule_event][:start_time], params[:schedule_event][:end_time] = 
    make_time(params[:schedule_event][:start_time]), make_time(params[:schedule_event][:end_time])
  
  params.require(:schedule_event)
  .permit(:title,
    :body,
    :day,
    :start_time,
    :end_time)
end

def outer_params
	params.permit(:user_id,
    			  :schedule_id)
end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div>
	<% if event %>
		<%= event.title %><br />
		<%= event.body %><br />
		<%= format_time(event.start_time) %> - <%= format_time(event.end_time) %>
	<% else %>
		
	<% end %>
</div>

app/views/events/new.html.erb
<article>
  <%= form_for @event, url: user_schedule_events_path(user_id: current_user.id, schedule_id: @parent_id) do |f| %>
  <fieldset class="flex third center">
    <label>
      <%= f.text_field :title, options = { class: "", placeholder: "Title" } %>
    </label>
    <label>
      <%= f.text_field :body, options = { class: "", placeholder: "Body" } %>
    </label>
    <label>
      <%= f.select :day, [['Monday','1'], ['Tuesday','2'],['Wednesday','3'], ['Thursday', '4'], ['Friday', '5'], ['Saturday', '6']], options = { class: "", placeholder: "Day" } %>
    </label>
    <label>
      <%= f.text_field :start_time, options = { class: "", placeholder: "Start Time" } %>
    </label>
    <label>
      <%= f.text_field :end_time, options = { class: "", placeholder: "End Time" } %>
    </label>
    <label>
      <%= f.submit "Create", :class => "button" %>
    </label>
  </fieldset>
  <% end %>
</article>