config/routes.rb
Rails.application.routes.draw do

  get   'credits'           => 'pages#credits'

  get   'signin'            => 'sessions#new'

  post  'signin'            => 'sessions#create'

  get   'signout'           => 'sessions#destroy'

  get   'signup'            => 'users#new'

  post  'signup'            => 'users#create'

  get   'profile'           => 'users#show_profile'

  get   'profile/:username' => 'users#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #concern :schedulable do
  #  resources :schedules, only: [:show, :edit, :update, :destroy, :new, :create] do
  #   collection do
  #      get 'list' => 'schedules#list'
  #    end
  #  end
  #end
  
  root :to => 'home#index'

resources :users, only: [:edit, :update, :destroy] do
  resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
    resources :events, only: [:show, :edit, :update, :destroy, :new, :create]
  end
  collection do
    get 'groups' => 'users#groups'
  end
end

  resources :groups, only: [:edit, :update, :destroy, :new, :create] do
    resources :schedules, only: [:index, :show, :edit, :update, :destroy, :new, :create]
    collection do
      get 'users' => 'groups#users'
    end
  end
  
end

app/views/layouts/_footer.html.erb
<div class="uk-section uk-section-secondary">
  <div class="uk-container">
    <div class="uk-grid-match uk-child-width-1-1@m" uk-grid>
      <div>
        <p>Built with <span style="color: salmon; font-weight: 800; font-size: 1.2em;" title="Love">&#10084;</span> from <a href="//github.com/therealdevelopers">the Real Developers</a> and <%= link_to 'others', credits_url %>.</p>
        <p>Workflower, 2017.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.erb
<nav>
  <a href= <%= root_path %> class="brand">
    <span>Workflower</span>
  </a>
  <input id="bmenu" type="checkbox" class="show" />
  <label for="bmenu" class="burger toggle pseudo button">&#8801;</label>
  <div class="menu">
    <% if current_user %>
      Logged as <%=current_user.login %>
      <%= link_to 'Profile', profile_path, html_options = { class: "pseudo button" } %>
      <%= link_to 'Schedules', user_schedules(user_id: current_user.id), html_options = { class: "pseudo button" } %>
      <%= link_to "Exit", signout_path, html_options = { class: "pseudo button" }  %>
    <% else %>
      <%= link_to "Sign Up", signup_path, html_options = { class: "pseudo button" } %>
      <%= link_to "Sign In", signin_path, html_options = { class: "pseudo button" } %>
    <% end %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="uk-background-primary uk-navbar-container" uk-navbar>
	<div class="uk-navbar-left">
		<ul class="uk-navbar-nav">
			<li><a href="/">Workflower</a></li>
		</ul>
	</div>
	<div class="uk-navbar-right">
		<ul class="uk-navbar-nav">
			<% if current_user %>
				<li><%= link_to 'Profile', profile_path %></li>
				<li><%= link_to 'Schedules', user_schedules_path(user_id: current_user.id) %></li>
				<li><%= link_to 'Sign Out', signout_path %></li>
			<% else %>
				<li><%= link_to 'Registration', signup_path %></li>
			<% end %>
		</ul>	 	
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>
			<%= full_title(yield(:title)) %>
		</title>
		<%= render 'partials/meta_tags' %>
	</head>
	<body>
		<%= render 'layouts/sidebar' %>
		<main>
			<%= yield %>
		</main>
		<footer id="footer">
			<%= render 'layouts/footer' %>
		</footer>
			<%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
	</body>
</html>